from pymathtools import *

prime = isprime(17)
print(f"isprime(17) Response: {prime}")
rectanglearea = rectanglearea(7, 4)
print(f"Rectangle with area of 7 and 4: {rectanglearea}")
trianglearea = trianglearea(6, 3)
print(f"Triangle with area of 6 and 3: {trianglearea}")
squarearea = squarearea(7)
print(f"Triangle with area of 7 and 7: {squarearea}")
cubevolume = cubevolume(3, 4, 7)
print(f"Cube with a volume of 3, 4, and 7: {squarearea}")
triangle = triangleperimeter(3, 4, 10)
print(triangle)
square = squareperimeter(410)
print(f"Perimeter of a square with a side of 410: {square}")
parallelogram = parallelogramperimeter(10, 410)
print(f"Perimeter of a parallelogram with the sides 10 and 410: {parallelogram}")
circlediam = circlediameter(14)
print(f"Circle diameter with a radius of 14: {circlediam}")
circlearea = circlearea(17)
print(f"Circle area with a radius of 17: {circlearea}")